## 1. Datenbereinigung Unternehmen 1–50

In [2]:
import os
os.getcwd()

'/Users/liviaglauser/Bachelorarbeit'

In [3]:
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_excel("Ergebnisse_1_50.xlsx")

In [5]:
id_col = "Unternehmensname Latin alphabet"

In [6]:
# Spalten mit USD droppen

In [7]:
usd_cols = df.columns[df.columns.str.contains("USD", case=False, na=False)]
df = df.drop(columns=usd_cols)

In [8]:
# Spalten mit tsd droppen

In [9]:
tsd_cols = df.columns[df.columns.str.contains("tsd", case=False, na=False)]
df = df.drop(columns=tsd_cols)

In [10]:
# Duplikate droppen

In [11]:
duplikate = df.columns[df.columns.str.contains(r"\.\d+$")]
df = df.drop(columns=duplikate)

In [12]:
# Spalten mit Letztes verf. Jahr droppen

In [13]:
df = df.loc[:, ~df.columns.str.contains("Letztes verf. Jahr", case=False)]

In [14]:
# n.v. mit NA ersetzen

In [15]:
df = df.replace("n.v.", pd.NA)

In [16]:
bilanzsumme_cols = [c for c in df.columns if "Bilanzsumme Aktiva" in c]
umlaufvermögen_cols = [c for c in df.columns if "Umlaufvermögen" in c]
zahlungsmittel_cols = [c for c in df.columns if "Zahlungsmittel & Zahlungsmitteläquivalente" in c]
kurz_verb_cols = [c for c in df.columns if "Kurzfristige Verbindlichkeiten" in c]
lang_verb_cols = [c for c in df.columns if "Langfristige Verbindlichkeiten" in c]
EK_cols = [c for c in df.columns if "Eigenkapital\nmil CHF" in c]
umsatz_cols = [c for c in df.columns if "Umsatz" in c]
EBIT_cols = [c for c in df.columns if "Betriebsgewinn/-verlust" in c]
finanzaufwendungen_cols = [c for c in df.columns if "Finanzaufwendungen" in c]
gewinn_verlust_cols = [c for c in df.columns if "Gewinn/Verlust vor Steuern" in c]
ROE_cols = [c for c in df.columns if "ROE basierend auf Gewinn/Verlust vor Steuern" in c]
ROA_cols = [c for c in df.columns if "ROA basierend auf Gewinn/Verlust vor Steuern" in c]
FK_zu_EK_cols = [c for c in df.columns if "Fremd- zu Eigenkapital" in c]
EK_quote_cols = [c for c in df.columns if "Eigenkapitalquote" in c]

In [17]:
# Wichtige Spalten erstellen

In [18]:
# Bilanzsumme Aktiva

In [19]:
bilanzsumme_long = df[[id_col] + bilanzsumme_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Bilanzsumme"
)

# Jahr aus Spaltennamen ziehen
bilanzsumme_long["Jahr"] = (
    bilanzsumme_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
bilanzsumme_long = bilanzsumme_long.drop(columns="Spalte")

In [20]:
# Eigenkapital

In [21]:
EK_long = df[[id_col] + EK_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Eigenkapital"
)

# Jahr aus Spaltennamen ziehen
EK_long["Jahr"] = (
    EK_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
EK_long = EK_long.drop(columns="Spalte")

In [22]:
# ROA

In [23]:
ROA_long = df[[id_col] + ROA_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="ROA"
)

# Jahr aus Spaltennamen ziehen
ROA_long["Jahr"] = (
    ROA_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
ROA_long = ROA_long.drop(columns="Spalte")

In [24]:
# Kurzfristige Verbindlichkeiten

In [25]:
kurz_verb_long = df[[id_col] + kurz_verb_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Kurzfristige_Verbindlichkeiten"
)

kurz_verb_long["Jahr"] = (
    kurz_verb_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

kurz_verb_long = kurz_verb_long.drop(columns="Spalte")

In [26]:
# Langfristige Verbindlichkeiten

In [27]:
lang_verb_long = df[[id_col] + lang_verb_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Langfristige_Verbindlichkeiten"
)

lang_verb_long["Jahr"] = (
    lang_verb_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

lang_verb_long = lang_verb_long.drop(columns="Spalte")

In [28]:
# Eigenkapital Quote

In [29]:
EK_quote_long = df[[id_col] + EK_quote_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="EK_Quote"
)

EK_quote_long["Jahr"] = (
    EK_quote_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

EK_quote_long = EK_quote_long.drop(columns="Spalte")

In [30]:
# Umsatz

In [31]:
umsatz_long = df[[id_col] + umsatz_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Umsatz"
)

umsatz_long["Jahr"] = (
    umsatz_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

umsatz_long = umsatz_long.drop(columns="Spalte")

In [32]:
# Zahlungsmittel

In [33]:
zahlungsmittel_long = df[[id_col] + zahlungsmittel_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Zahlungsmittel"
)

# Jahr aus Spaltennamen ziehen
zahlungsmittel_long["Jahr"] = (
    zahlungsmittel_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
zahlungsmittel_long = zahlungsmittel_long.drop(columns="Spalte")

In [34]:
panel = (
    bilanzsumme_long
    .merge(zahlungsmittel_long, on=[id_col, "Jahr"], how="outer")
    .merge(ROA_long,            on=[id_col, "Jahr"], how="outer")
    .merge(EK_long,             on=[id_col, "Jahr"], how="outer")
    .merge(kurz_verb_long,      on=[id_col, "Jahr"], how="outer")
    .merge(lang_verb_long,      on=[id_col, "Jahr"], how="outer")
    .merge(EK_quote_long,       on=[id_col, "Jahr"], how="outer")
    .merge(umsatz_long,         on=[id_col, "Jahr"], how="outer")
)

Unternehmensdaten_1_50 = panel.sort_values([id_col, "Jahr"]).reset_index(drop=True)

In [35]:
#Unternehmensdaten.to_csv("Unternehmensdaten.csv", index=False)

## 2. Datenbereinigung Unternehmen 50–70

In [37]:
df = pd.read_excel("Ergebnisse_50_70.xlsx")

In [38]:
# Spalten mit USD droppen

In [39]:
usd_cols = df.columns[df.columns.str.contains("USD", case=False, na=False)]
df = df.drop(columns=usd_cols)

In [40]:
# Spalten mit tsd droppen

In [41]:
tsd_cols = df.columns[df.columns.str.contains("tsd", case=False, na=False)]
df = df.drop(columns=tsd_cols)

In [42]:
# Duplikate droppen

In [43]:
duplikate = df.columns[df.columns.str.contains(r"\.\d+$")]
df = df.drop(columns=duplikate)

In [44]:
# Spalten mir Letztes verf. Jahr droppen

In [45]:
df = df.loc[:, ~df.columns.str.contains("Letztes verf. Jahr", case=False)]

In [46]:
# n.v. mit NA ersetzen

In [47]:
df = df.replace("n.v.", pd.NA)

In [48]:
bilanzsumme_cols = [c for c in df.columns if "Bilanzsumme Aktiva" in c]
umlaufvermögen_cols = [c for c in df.columns if "Umlaufvermögen" in c]
zahlungsmittel_cols = [c for c in df.columns if "Zahlungsmittel & Zahlungsmitteläquivalente" in c]
kurz_verb_cols = [c for c in df.columns if "Kurzfristige Verbindlichkeiten" in c]
lang_verb_cols = [c for c in df.columns if "Langfristige Verbindlichkeiten" in c]
EK_cols = [c for c in df.columns if "Eigenkapital\nmil CHF" in c]
umsatz_cols = [c for c in df.columns if "Umsatz" in c]
EBIT_cols = [c for c in df.columns if "Betriebsgewinn/-verlust" in c]
finanzaufwendungen_cols = [c for c in df.columns if "Finanzaufwendungen" in c]
gewinn_verlust_cols = [c for c in df.columns if "Gewinn/Verlust vor Steuern" in c]
ROE_cols = [c for c in df.columns if "ROE basierend auf Gewinn/Verlust vor Steuern" in c]
ROA_cols = [c for c in df.columns if "ROA basierend auf Gewinn/Verlust vor Steuern" in c]
FK_zu_EK_cols = [c for c in df.columns if "Fremd- zu Eigenkapital" in c]
EK_quote_cols = [c for c in df.columns if "Eigenkapitalquote" in c]

In [49]:
# Wichtige Spalten erstellen

In [50]:
# Bilanzsumme Aktiva

In [51]:
bilanzsumme_long = df[[id_col] + bilanzsumme_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Bilanzsumme"
)

# Jahr aus Spaltennamen ziehen
bilanzsumme_long["Jahr"] = (
    bilanzsumme_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
bilanzsumme_long = bilanzsumme_long.drop(columns="Spalte")

In [52]:
# Eigenkapital

In [53]:
EK_long = df[[id_col] + EK_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Eigenkapital"
)

# Jahr aus Spaltennamen ziehen
EK_long["Jahr"] = (
    EK_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
EK_long = EK_long.drop(columns="Spalte")

In [54]:
# ROA

In [55]:
ROA_long = df[[id_col] + ROA_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="ROA"
)

# Jahr aus Spaltennamen ziehen
ROA_long["Jahr"] = (
    ROA_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
ROA_long = ROA_long.drop(columns="Spalte")

In [56]:
# Kurzfristige Verbindlichkeiten

In [57]:
kurz_verb_long = df[[id_col] + kurz_verb_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Kurzfristige_Verbindlichkeiten"
)

kurz_verb_long["Jahr"] = (
    kurz_verb_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

kurz_verb_long = kurz_verb_long.drop(columns="Spalte")

In [58]:
# Langfristige Verbindlichkeiten

In [59]:
lang_verb_long = df[[id_col] + lang_verb_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Langfristige_Verbindlichkeiten"
)

lang_verb_long["Jahr"] = (
    lang_verb_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

lang_verb_long = lang_verb_long.drop(columns="Spalte")

In [60]:
# Eigenkapital Quote

In [61]:
EK_quote_long = df[[id_col] + EK_quote_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="EK_Quote"
)

EK_quote_long["Jahr"] = (
    EK_quote_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

EK_quote_long = EK_quote_long.drop(columns="Spalte")

In [62]:
# Umsatz

In [63]:
umsatz_long = df[[id_col] + umsatz_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Umsatz"
)

umsatz_long["Jahr"] = (
    umsatz_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

umsatz_long = umsatz_long.drop(columns="Spalte")

In [64]:
# Zahlungsmittel

In [65]:
zahlungsmittel_long = df[[id_col] + zahlungsmittel_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Zahlungsmittel"
)

# Jahr aus Spaltennamen ziehen
zahlungsmittel_long["Jahr"] = (
    zahlungsmittel_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
zahlungsmittel_long = zahlungsmittel_long.drop(columns="Spalte")

In [66]:
panel = (
    bilanzsumme_long
    .merge(zahlungsmittel_long, on=[id_col, "Jahr"], how="outer")
    .merge(ROA_long,            on=[id_col, "Jahr"], how="outer")
    .merge(EK_long,             on=[id_col, "Jahr"], how="outer")
    .merge(kurz_verb_long,      on=[id_col, "Jahr"], how="outer")
    .merge(lang_verb_long,      on=[id_col, "Jahr"], how="outer")
    .merge(EK_quote_long,       on=[id_col, "Jahr"], how="outer")
    .merge(umsatz_long,         on=[id_col, "Jahr"], how="outer")
)

Unternehmensdaten_50_70 = panel.sort_values([id_col, "Jahr"]).reset_index(drop=True)

In [67]:
#Unternehmensdaten_50_70.to_csv("Unternehmensdaten_50_70.csv", index=False)

## 3. Datenbereinigung Unternehmen 70–90

In [69]:
df = pd.read_excel("Ergebnisse_70_90.xlsx")

In [70]:
# Spalten mit USD droppen

In [71]:
usd_cols = df.columns[df.columns.str.contains("USD", case=False, na=False)]
df = df.drop(columns=usd_cols)

In [72]:
# Spalten mit tsd droppen

In [73]:
tsd_cols = df.columns[df.columns.str.contains("tsd", case=False, na=False)]
df = df.drop(columns=tsd_cols)

In [74]:
# Duplikate droppen

In [75]:
duplikate = df.columns[df.columns.str.contains(r"\.\d+$")]
df = df.drop(columns=duplikate)

In [76]:
# Spalten mit Letztes verf. Jahr droppen

In [77]:
df = df.loc[:, ~df.columns.str.contains("Letztes verf. Jahr", case=False)]

In [78]:
# n.v. mit NA ersetzen

In [79]:
df = df.replace("n.v.", pd.NA)

In [80]:
bilanzsumme_cols = [c for c in df.columns if "Bilanzsumme Aktiva" in c]
umlaufvermögen_cols = [c for c in df.columns if "Umlaufvermögen" in c]
zahlungsmittel_cols = [c for c in df.columns if "Zahlungsmittel & Zahlungsmitteläquivalente" in c]
kurz_verb_cols = [c for c in df.columns if "Kurzfristige Verbindlichkeiten" in c]
lang_verb_cols = [c for c in df.columns if "Langfristige Verbindlichkeiten" in c]
EK_cols = [c for c in df.columns if "Eigenkapital\nmil CHF" in c]
umsatz_cols = [c for c in df.columns if "Umsatz" in c]
EBIT_cols = [c for c in df.columns if "Betriebsgewinn/-verlust" in c]
finanzaufwendungen_cols = [c for c in df.columns if "Finanzaufwendungen" in c]
gewinn_verlust_cols = [c for c in df.columns if "Gewinn/Verlust vor Steuern" in c]
ROE_cols = [c for c in df.columns if "ROE basierend auf Gewinn/Verlust vor Steuern" in c]
ROA_cols = [c for c in df.columns if "ROA basierend auf Gewinn/Verlust vor Steuern" in c]
FK_zu_EK_cols = [c for c in df.columns if "Fremd- zu Eigenkapital" in c]
EK_quote_cols = [c for c in df.columns if "Eigenkapitalquote" in c]

In [81]:
# Wichtige Spalten erstellen

In [82]:
# Bilanzsumme Aktiva

In [83]:
bilanzsumme_long = df[[id_col] + bilanzsumme_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Bilanzsumme"
)

# Jahr aus Spaltennamen ziehen
bilanzsumme_long["Jahr"] = (
    bilanzsumme_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
bilanzsumme_long = bilanzsumme_long.drop(columns="Spalte")

In [84]:
# Eigenkapital

In [85]:
EK_long = df[[id_col] + EK_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Eigenkapital"
)

# Jahr aus Spaltennamen ziehen
EK_long["Jahr"] = (
    EK_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
EK_long = EK_long.drop(columns="Spalte")

In [86]:
# ROA

In [87]:
ROA_long = df[[id_col] + ROA_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="ROA"
)

# Jahr aus Spaltennamen ziehen
ROA_long["Jahr"] = (
    ROA_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
ROA_long = ROA_long.drop(columns="Spalte")

In [88]:
# Kurzfristige Verbindlichkeiten

In [89]:
kurz_verb_long = df[[id_col] + kurz_verb_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Kurzfristige_Verbindlichkeiten"
)

kurz_verb_long["Jahr"] = (
    kurz_verb_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

kurz_verb_long = kurz_verb_long.drop(columns="Spalte")

In [90]:
# Langfristige Verbindlichkeiten

In [91]:
lang_verb_long = df[[id_col] + lang_verb_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Langfristige_Verbindlichkeiten"
)

lang_verb_long["Jahr"] = (
    lang_verb_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

lang_verb_long = lang_verb_long.drop(columns="Spalte")

In [92]:
# Eigenkapital Quote

In [93]:
EK_quote_long = df[[id_col] + EK_quote_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="EK_Quote"
)

EK_quote_long["Jahr"] = (
    EK_quote_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

EK_quote_long = EK_quote_long.drop(columns="Spalte")

In [94]:
# Umsatz

In [95]:
umsatz_long = df[[id_col] + umsatz_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Umsatz"
)

umsatz_long["Jahr"] = (
    umsatz_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)

umsatz_long = umsatz_long.drop(columns="Spalte")

In [96]:
# Zahlungsmittel

In [97]:
zahlungsmittel_long = df[[id_col] + zahlungsmittel_cols].melt(
    id_vars=id_col,
    var_name="Spalte",
    value_name="Zahlungsmittel"
)

# Jahr aus Spaltennamen ziehen
zahlungsmittel_long["Jahr"] = (
    zahlungsmittel_long["Spalte"]
    .astype(str)
    .str.extract(r"(\d{4})")
    .astype(int)
)
# Aufräumen
zahlungsmittel_long = zahlungsmittel_long.drop(columns="Spalte")

In [98]:
panel = (
    bilanzsumme_long
    .merge(zahlungsmittel_long, on=[id_col, "Jahr"], how="outer")
    .merge(ROA_long,            on=[id_col, "Jahr"], how="outer")
    .merge(EK_long,             on=[id_col, "Jahr"], how="outer")
    .merge(kurz_verb_long,      on=[id_col, "Jahr"], how="outer")
    .merge(lang_verb_long,      on=[id_col, "Jahr"], how="outer")
    .merge(EK_quote_long,       on=[id_col, "Jahr"], how="outer")
    .merge(umsatz_long,         on=[id_col, "Jahr"], how="outer")
)

Unternehmensdaten_70_90 = panel.sort_values([id_col, "Jahr"]).reset_index(drop=True)

In [99]:
#Unternehmensdaten_70_90.to_csv("Unternehmensdaten_70_90.csv", index=False)

## 4. Zusammenführen der Unternehmensdaten

In [101]:
# Bereinigte Daten umbenennen

In [102]:
df1 = Unternehmensdaten_1_50
df2 = Unternehmensdaten_50_70
df3 = Unternehmensdaten_70_90

In [103]:
# dataframes zusammenfügen

In [104]:
df_all = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

In [105]:
df_all = df_all.sort_values([id_col, "Jahr"]).reset_index(drop=True)

In [106]:
#df_all.to_csv("Unternehmensdaten_final_.csv", index=False)

## 5. Filterung 2016–2024

In [108]:
df = df_all

In [109]:
# Datenzeitrum von 2016 bis 2025 setzen

In [110]:
years = list(range(2016, 2025))

# Nur relevante Jahre
df_sub = df[df["Jahr"].isin(years)]

# Unternehmen, die in allen Jahren vorhanden sind
valid_companies = (
    df_sub
    .groupby(id_col)
    .filter(lambda x: 
            x["Jahr"].nunique() == len(years) and
            x.notna().all().all()
           )
)

# Einzelne Unternehmen
valid_companies[id_col].nunique()

318

In [111]:
df_2016_2025 = df[df["Jahr"].isin(range(2016, 2025))]

In [112]:
# Unternehmen behalten, die KEIN einziges NaN haben
df_no_nan_companies = (
    df_2016_2025
    .groupby(id_col)
    .filter(lambda x: not x.isna().any().any())
)

In [113]:
Unternehmen = df_no_nan_companies

In [114]:
#df_no_nan_companies.to_csv("Unternehmensdaten_16_24.csv", index=False)

## 6. Zinsdaten und berechnete Variablen hinzufügen

In [116]:
# Zinsdaten als Dataframe schreiben
Zins = pd.DataFrame({
    "Jahr": [
        2016,2017,2018,2019,
        2020,2021,2022,2023,2024
    ],
    "Zinsschock": [
        -0.44,
        -0.775,-0.04,1.6,3.62,0.25,22.6,-20.407,-33.391
    ],
    "ABS": [
        2.84,
        0.775,0.72,2,4.9,0.25,64.6,44.581,50.823
    ]
})

In [117]:
# Unternehmens- und Zinsdaten zusammenfügen
df_merged = Unternehmen.merge(
    Zins,
    on="Jahr",
    how="left"
)

In [118]:
df_merged["Bilanzsumme"] = pd.to_numeric(
    df_merged["Bilanzsumme"],
    errors="coerce"
)

In [119]:
# Zinswernde-Dummy erstellen
df_merged["Zinswende_Dummy"] = (df_merged["Jahr"] >= 2022).astype(int)

In [120]:
# Variablen Berechnen

In [121]:
df_merged["Cash_Ratio"] = (
    df_merged["Zahlungsmittel"] / df_merged["Bilanzsumme"]
)

In [122]:
df_merged["Groesse_Log_Bilanzsumme"] = np.log(df_merged["Bilanzsumme"])

In [123]:
pre_years = range(2016, 2022)  # 2016–2021

In [124]:
df_merged["Leverage"] = (
    (df_merged["Kurzfristige_Verbindlichkeiten"]
     + df_merged["Langfristige_Verbindlichkeiten"])
    / df_merged["Bilanzsumme"]
)

In [125]:
leverage_exante = (
    df_merged[df_merged["Jahr"].isin(pre_years)]
    .groupby(id_col)["Leverage"]
    .mean()
)

In [126]:
df_merged["Leverage_exante"] = df_merged[company_col].map(leverage_exante)

In [127]:
liquidity_exante = (
    df_merged[df_merged["Jahr"].isin(pre_years)]
    .groupby(id_col)["Cash_Ratio"]
    .mean()
)

In [128]:
df_merged["Liquidity_exante"] = df_merged[id_col].map(liquidity_exante)

In [129]:
df_merged["STDebtShare"] = (
    df_merged["Kurzfristige_Verbindlichkeiten"] /
    (df_merged["Kurzfristige_Verbindlichkeiten"]
     + df_merged["Langfristige_Verbindlichkeiten"])
)

In [130]:
stdebt_exante = (
    df_merged[df_merged["Jahr"].isin(pre_years)]
    .groupby(company_col)["STDebtShare"]
    .mean()
)

In [131]:
df_merged["STDebtShare_exante"] = df_merged[company_col].map(stdebt_exante)

## 7. Letzte Missing-Value Bereinigung

In [133]:
df = df_merged

In [134]:
df = df.replace(["n.s.", "n.s", "NA", "na", ""], np.nan)

/var/folders/nd/8mtd0whj6w70jg2l1j9rsy0r0000gn/T/ipykernel_32701/1155019838.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(["n.s.", "n.s", "NA", "na", ""], np.nan)

In [135]:
df[df.isna().any(axis=1)]

,Unternehmensname Latin alphabet,Bilanzsumme,Jahr,Zahlungsmittel,ROA,Eigenkapital,Kurzfristige_Verbindlichkeiten,Langfristige_Verbindlichkeiten,EK_Quote,Umsatz,Zinsschock,ABS,Zinswende_Dummy,Cash_Ratio,Groesse_Log_Bilanzsumme,Leverage,Leverage_exante,Liquidity_exante,STDebtShare,STDebtShare_exante
0,ADDEX THERAPEUTICS SA,1.683000,2016,1.416000,NaN,0.219000,1.250000,0.214000,13.012,0.000000,-0.440,2.840,0,0.841355,0.520578,0.869875,0.375678,0.911484,0.853825,0.773563
1,ADDEX THERAPEUTICS SA,3.063000,2017,2.591000,NaN,1.343000,1.477000,0.243000,43.846,0.000000,-0.775,0.775,0,0.845903,1.119395,0.561541,0.375678,0.911484,0.858721,0.773563
6,ADDEX THERAPEUTICS SA,8.282000,2022,6.961000,NaN,4.913000,3.282000,0.087000,59.321,1.422000,22.600,64.600,1,0.840497,2.114084,0.406786,0.375678,0.911484,0.974176,0.773563
7,ADDEX THERAPEUTICS SA,4.642000,2023,3.866000,NaN,1.145000,2.893000,0.604000,24.666,1.613000,-20.407,44.581,1,0.832831,1.535145,0.753339,0.375678,0.911484,0.827281,0.773563
1331,HOCHDORF HOLDING AG,16.034000,2024,15.783000,NaN,13.791000,2.242000,0.001000,86.011,241.189000,-33.391,50.823,1,0.984346,2.774711,0.139890,0.524033,0.081644,0.999554,0.401213
2077,RELIEF THERAPEUTICS HOLDING AG,76.390000,2023,14.556000,NaN,52.228000,6.909000,17.253000,68.370,6.033000,-20.407,44.581,1,0.190549,4.335852,0.316298,0.286256,0.127340,0.285945,0.319424
2175,SANTHERA PHARMACEUTICALS HOLDING LTD,63.726000,2022,1.353000,NaN,-43.686000,49.414000,57.998000,-68.553,7.473000,22.600,64.600,1,0.021232,4.154593,1.685529,0.751223,0.331817,0.460042,0.326703
2763,WISEKEY INTERNATIONAL HOLDING AG,34.170112,2016,5.304536,NaN,1.942592,25.990296,6.237224,5.685,11.137392,-0.440,2.840,0,0.155239,3.531351,0.943149,0.756909,0.287882,0.806463,0.595501

In [136]:
unternehmen_loeschen = [
    "ADDEX THERAPEUTICS SA",
    "HOCHDORF HOLDING AG",
    "RELIEF THERAPEUTICS HOLDING AG",
    "SANTHERA PHARMACEUTICALS HOLDING LTD",
    "WISEKEY INTERNATIONAL HOLDING AG"
]

df = df[~df['Unternehmensname Latin alphabet'].isin(unternehmen_loeschen)]

In [137]:
df

,Unternehmensname Latin alphabet,Bilanzsumme,Jahr,Zahlungsmittel,ROA,Eigenkapital,Kurzfristige_Verbindlichkeiten,Langfristige_Verbindlichkeiten,EK_Quote,Umsatz,Zinsschock,ABS,Zinswende_Dummy,Cash_Ratio,Groesse_Log_Bilanzsumme,Leverage,Leverage_exante,Liquidity_exante,STDebtShare,STDebtShare_exante
9,ADECCO GROUP AG,10815.676995,2016,1208.048683,10.249,3986.132268,4686.543473,2143.001254,36.855,24319.476503,-0.440,2.840,0,0.111694,9.288752,0.631449,0.646262,0.135443,0.686216,0.673901
10,ADECCO GROUP AG,11568.104335,2017,1125.229158,9.494,4189.782581,5216.758881,2161.562873,36.218,27674.554960,-0.775,0.775,0,0.097270,9.356007,0.637816,0.646262,0.135443,0.707039,0.673901
11,ADECCO GROUP AG,10956.870613,2018,735.118300,7.481,4046.533096,4905.674423,2004.663094,36.931,26909.614214,-0.040,0.720,0,0.067092,9.301722,0.630685,0.646262,0.135443,0.709904,0.673901
12,ADECCO GROUP AG,11497.820557,2019,1469.449964,10.179,4294.143937,4866.261392,2337.415228,37.347,25480.980247,1.600,2.000,0,0.127802,9.349913,0.626525,0.646262,0.135443,0.675525,0.673901
13,ADECCO GROUP AG,10588.284394,2020,1605.760041,0.694,3479.687416,4824.849363,2283.747614,32.864,21151.698430,3.620,4.900,0,0.151654,9.267503,0.671364,0.646262,0.135443,0.678734,0.673901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,ZWAHLEN & MAYR SA,52.759000,2020,5.152000,-3.717,38.154000,9.161000,5.444000,72.318,41.895000,3.620,4.900,0,0.097652,3.965734,0.276825,0.296519,0.069610,0.627251,0.671236
2894,ZWAHLEN & MAYR SA,52.071000,2021,2.726000,2.278,39.170000,8.860000,4.041000,75.224,55.776000,0.250,0.250,0,0.052352,3.952608,0.247758,0.296519,0.069610,0.686768,0.671236
2895,ZWAHLEN & MAYR SA,58.734000,2022,1.714000,2.556,40.364000,14.063000,4.307000,68.723,56.249000,22.600,64.600,1,0.029182,4.073019,0.312766,0.296519,0.069610,0.765542,0.671236
2896,ZWAHLEN & MAYR SA,59.670000,2023,0.905000,1.373,41.071000,14.092000,4.507000,68.830,53.776000,-20.407,44.581,1,0.015167,4.088829,0.311698,0.296519,0.069610,0.757675,0.671236
2897,ZWAHLEN & MAYR SA,54.047000,2024,1.294000,-9.712,36.425000,14.727000,2.895000,67.395,40.688000,-33.391,50.823,1,0.023942,3.989854,0.326050,0.296519,0.069610,0.835717,0.671236

In [138]:
df.isna().sum().sum()

0

In [139]:
#df.to_csv("final_df.csv", index=False)